/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'new_app_mahmoud';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String NEOSANSARABIC = 'assets/fonts/NeoSansArabic.ttf';
  static const String ANALYSIS = 'assets/images/analysis.png';
  static const String ANALYSISICON = 'assets/images/analysisIcon.png';
  static const String LABREPORT = 'assets/images/labReport.png';
  static const String LABSICON = 'assets/images/labsIcon.png';
  static const String REGISTER = 'assets/images/register.png';
}
