// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'new_app_mahmoud';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String NEOSANSARABICLIGHT = 'NeoSansArabicLight';
  static const String NEOSANSARABICMEDIUM = 'NeoSansArabicMedium';
  static const String NEOSANSARABICULTRA = 'NeoSansArabicUltra';
  static const String NEO_SANS_MEDIUM = 'Neo_Sans_Medium';
}
